# modules/observability/outputs.tf

output "sns_topic_arn" {
  description = "The ARN of the SNS topic used for alerts."
  value       = aws_sns_topic.alerts.arn
}

output "dashboard_url" {
  description = "URL of the CloudWatch Dashboard."
  value       = "https://${var.aws_region}.console.aws.amazon.com/cloudwatch/home?region=${var.aws_region}#dashboards:name=${aws_cloudwatch_dashboard.main.dashboard_name}"
}

output "app_requests_metric_name" {
  description = "The name of the custom CloudWatch metric generated by the app requests filter."
  value       = aws_cloudwatch_log_metric_filter.app_requests_metric_filter.metric_transformation[0].name
}

output "app_requests_metric_namespace" {
  description = "The namespace of the custom CloudWatch metric generated by the app requests filter."
  value       = aws_cloudwatch_log_metric_filter.app_requests_metric_filter.metric_transformation[0].namespace
}